import { NextRequest, NextResponse } from 'next/server'
import { createServiceClient } from '@/lib/supabase/server'
import { getAuthContext, orgMismatch } from '@/lib/auth/guards'

// Brand brain JSONB sections. `revision.section` is generated by Claude, so it
// must be validated against this allowlist before being used as a column name.
const VALID_BRAIN_SECTIONS = [
  'identity',
  'audience',
  'voice',
  'products',
  'content_pillars',
  'platforms',
  'competitive',
  'visual_identity',
  'operations',
  'performance_learning',
] as const

export async function POST(_req: NextRequest, { params }: { params: Promise<{ id: string }> }) {
  const { id } = await params

  const ctx = await getAuthContext()
  if (!ctx) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  if (ctx.role !== 'admin') return NextResponse.json({ error: 'Forbidden' }, { status: 403 })

  const service = await createServiceClient()

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const { data: revision } = await (service as any)
    .from('brand_brain_revisions')
    .select('*')
    .eq('id', id)
    .eq('status', 'pending')
    .single()

  if (!revision) return NextResponse.json({ error: 'Revision not found or already reviewed' }, { status: 404 })

  // El service client bypasea RLS: la revisión debe pertenecer a la org del admin.
  const { data: ownerClient } = await service
    .from('clients')
    .select('organization_id')
    .eq('id', revision.client_id as string)
    .single()
  if (!ownerClient || orgMismatch(ctx, ownerClient.organization_id)) {
    return NextResponse.json({ error: 'Forbidden' }, { status: 403 })
  }

  // Validate the section before using it as a column name (injection / typo guard).
  const section = revision.section as string
  if (!(VALID_BRAIN_SECTIONS as readonly string[]).includes(section)) {
    return NextResponse.json({ error: `Invalid brand brain section: ${section}` }, { status: 400 })
  }

  // Apply the proposed changes to the brand brain
  const { data: brain } = await service
    .from('brand_brains')
    .select('*')
    .eq('client_id', revision.client_id)
    .single()

  if (!brain) return NextResponse.json({ error: 'Brand brain not found' }, { status: 404 })

  const currentSection = (brain as unknown as Record<string, unknown>)[section] ?? {}
  const merged = { ...(currentSection as Record<string, unknown>), ...(revision.proposed_changes as Record<string, unknown>) }

  const { error: brainError } = await service
    .from('brand_brains')
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    .update({
      [section]: merged,
      version: ((brain as unknown as Record<string, number>).version ?? 1) + 1,
      updated_at: new Date().toISOString(),
    } as any)
    .eq('client_id', revision.client_id)

  if (brainError) {
    return NextResponse.json(
      { error: 'Failed to update brand brain', detail: brainError.message },
      { status: 500 },
    )
  }

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  await (service as any)
    .from('brand_brain_revisions')
    .update({ status: 'approved', reviewed_by: ctx.userId, reviewed_at: new Date().toISOString() })
    .eq('id', id)

  return NextResponse.json({ ok: true })
}
